version: '3.8'
volumes:
  node_modules:
    driver: local
services:
  clasp:
    build:
      context: ./
      dockerfile: dockerfiles/clasp/Dockerfile
    volumes:
      - .:/usr/src

      # not sync directories
      - node_modules:/usr/src/node_modules
    environment:
      TZ: Asia/Tokyo
      LANG: en_US.UTF-8
    working_dir: /usr/src
    tty: true
  eslint:
    build:
      context: ./
      dockerfile: dockerfiles/eslint/Dockerfile
    volumes:
      - ./src:/usr/src/src
      - ./eslint.config.js:/usr/src/eslint.config.js
      - ./dockerfiles/eslint/package.json:/usr/src/package.json
      - ./dockerfiles/eslint/package-lock.json:/usr/src/package-lock.json
    working_dir: /usr/src
    command: npx eslint .

